# Site settings
title: Lame No More
email: contact@lamenomore.com
description: > # this means to ignore newlines until "baseurl:"
  Your weekly dose of (probably shitty but sometimes fun) Top 10 music that you should know, straight to your inbox.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lamenomore.com" # the base hostname & protocol for your site
twitter_username: lamenomore
# github_username:  Bootstragram/lamenomore

# Build settings
markdown: kramdown
